name: prospector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+35

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_route: ^3.1.3
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0-nullsafety
  charts_flutter: ^0.12.0
  cloud_firestore: ^3.1.4
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.3
  dartz: ^0.10.1
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.2.3
  flash: ^2.0.3
  flutter:
    sdk: flutter
  flutter_chips_input: ^1.10.0
  flutter_contacts: ^1.1.1+2
  flutter_facebook_auth: ^3.5.0
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^9.1.4
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_riverpod: ^0.14.0+3
  flutter_sticky_header: ^0.6.0
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^0.14.2
  google_mobile_ads: ^0.13.2+1
  google_sign_in: ^5.0.5
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  permission_handler: ^8.1.2
  purchases_flutter: ^3.6.0
  random_string: ^2.3.1
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.2.0
  table_calendar: ^3.0.3
  timeago: ^3.1.0
  url_launcher: ^6.0.17

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  hive_generator: ^1.1.1
  lint: ^1.5.3

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/prospector_icon.png"
  image_path_android: "assets/icon/android_foreground.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/android_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # Enabling codegen for internationalization
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: AppLocalizations
